---
- name: turn off swap for the time being
  command: swapoff {{ swapfile_path }}
  ignore_errors: yes

- name: remove previouse swapfile
  file: path={{ swapfile_path }} state=absent

- name: create new swapfile
  command: fallocate -l {{ swapfile_size }} {{ swapfile_path }}

- name: format the file for swap
  command: mkswap {{ swapfile_path }}

- name: change swapfile permissions
  file: path={{ swapfile_path }} owner=root group=root mode=0600

- name: add the file to swap
  command: swapon {{ swapfile_path }}

- name: write swap entry in fstab
  mount: name=none src={{ swapfile_path }} fstype=swap opts=sw passno=0 dump=0 state=present
