---
- hosts: test
  vars:
  connection: local
  sudo: yes
  roles:
    - { role: common, tags: "common" }
    - { role: swapon, tags: "swapon" }
    - { role: mongodb, tags: "mongodb" }
    - { role: nodejs, tags: "nodejs" }
    # - { role: testbed, tags: "testbed" }
    # - { role: webserver, tags: "webserver" }
    # - { role: samba, tags: "samba" }
    # - { role: ftpd, tags: "ftpd" }
    # - { role: nfs, tags: "nfs" }
